channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=23.0.1
- pip:
  - mlflow==2.15.0
  - cloudpickle==3.0.0
  - lz4==4.3.3
  - numpy==1.26.4
  - psutil==5.9.8
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
